 inherit_from:
  - .rubocop_airbnb.yml

 Rails:
   Enabled: true

 LineLength:
  Max: 130

 AllCops:
   Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'path/ruby'
    - 'spec/spec_helper.rb'
    
