default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  # 以下の3つを追加
  username: pg-taka
  password: pg-taka
  # RailsサーバとPostgreSQLサーバが同じ場合
  host: localhost

development:
  <<: *default
  database: myapp_development
  host: db
  username: postgres
  password:

test:
  <<: *default
  database: myapp_test
  host: db
  username: postgres
  password:
  